name: Blog

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 * * * *

jobs:
  github-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACTION_ACCESS }}
          user: jack-Zhang
          template: classic
